name: Merge branch with labeled
on: [pull_request]
jobs:
  merge-staging-branch:
    if: contains(github.event.pull_request.labels.*.name, 'merged in staging')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge by labeled
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          target_branch: 'staging'
          github_token: ${{ github.token }}
